version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: JobApplicationTracker.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - UseInMemoryDatabase=true
    volumes:
      - api-data:/app/Data
    networks:
      - jobtracker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    networks:
      - jobtracker-network

volumes:
  api-data:

networks:
  jobtracker-network:
    driver: bridge